### ISSUE TITLE
Invalid argument(s): Illegal argument in isolate message: object is unsendable

### ISSUE THREAD

**Issue by fabianbrandscheid** [machinescream/worker_manager#87]
Hi,

after updating to worker_manager 6.x.x I get the following error when calling the worker_manager with an non primitive data type:

_Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _AsyncCompleter@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)_

Here is a little code snippet. 

```

workerManager.execute<ResultEntity <T>>(() => handleCacheManagerFromEncryptedArgumentEntity(
                ArgumentEntity<T>(
                  payload: encrypted,
                  fromJson: fromJson,
                ),
              ));

// top-level function
ResultEntity<T>
    handleCacheManagerFromEncryptedArgumentEntity<T extends Object>(
        ArgumentEntity <T> args) {
  final json = jsonDecode(args.payload);
  final cacheItem = CacheItem(json);

  final T model = args.fromJson(h4uInternalCacheItem.json!);

  return ResultEntity <T>(
    // remove payload to increase performance
    cacheItem: cacheItem.copyWith(
      json: {},
    ),
    model: model,
  );
}
```

Before the Update the same code with the "old syntax" works fine. Any ideas? Thank you in advice!

Beste regards.

**Comment by machinescream** [comment]
Hi, looks weird. worker_manager has no affect to dart isolates api. Send me exact versions of dependencies you have used before update

**Comment by machinescream** [comment]
here I tried old version of worker_manager. Sa
<img width="1414" alt="Screenshot 2023-06-23 at 13 06 20" src="https://github.com/machinescream/worker_manager/assets/42138594/b78a99a7-3f21-495e-a457-f8f6826f72c3">
me error

**Comment by machinescream** [comment]
@fabianbrandscheid what version of dart are you using?

**Comment by fabianbrandscheid** [comment]
@machinescream 
This is my current flutter and dart version:
```
Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 3.0.3 • DevTools 2.23.1
```
Before the update I used worker_manager version 5.0.3

**Comment by machinescream** [comment]
> @machinescream This is my current flutter and dart version:
> 
> ```
> Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
> Tools • Dart 3.0.3 • DevTools 2.23.1
> ```
> 
> Before the update I used worker_manager version 5.0.3

Also provide minimal example to test

**Comment by fabianbrandscheid** [comment]
@machinescream the problem seems to be that we used the `arg1` in worker_manager 5.0.3 to pass a function that's gets executed in `fun1`.
Here a little example:
```
void main() async {
  await Executor().warmUp(log: true);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final computeResults = [];
  final executorResults = [];
  var computeTaskRun = 0;
  var executorTaskRun = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Row(
              children: [
                CupertinoButton(
                  child: Text('run executor'),
                  onPressed: () {
                    void testFunction() {
                      print('hello');
                    }

                    final argument = Test(testFunction, "sa", 42);
                    setState(() {
                      executorTaskRun++;
                      Executor()
                          .execute(
                        arg1: argument,
                        fun1: (args, port) => func(args),
                      )
                          .then((value) {
                        setState(() {
                          executorResults.add(value);
                        });
                      });
                    });
                  },
                )
              ],
            ),
          ],
        ),
      ),
    );
  }
}

int func(Test args) {
  final test = args as Test;
  test.pressMe();

  return test.i;
}

class Test {
  final VoidCallback pressMe;
  final String t;
  final int i;

  const Test(this.pressMe, this.t, this.i);
}


```

With worker_manager 6.x.x the `arg1` parameter isn't  available anymore. So I have to pass the arguments to the function what results to this error.


```
void main() async {
  workerManager.log = true;
  await workerManager.init();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      showPerformanceOverlay: true,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final computeResults = [];
  final executorResults = [];
  var computeTaskRun = 0;
  var executorTaskRun = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Row(
              children: [
                CupertinoButton(
                    child: Text('run executor'),
                    onPressed: () {
                      void testFunction() {
                        print('hello');
                      }

                      final argument = Test(testFunction, "sd", 42);

                      workerManager.execute(() {
                        func(argument);
                      }).then((value) {
                        setState(() {
                          executorResults.add(value);
                        });
                      });
                    })
              ],
            ),
          ],
        ),
      ),
    );
  }
}

int func(Test args) {
  final test = args as Test;
  test.pressMe();

  return test.i;
}

class Test {
  final VoidCallback pressMe;
  final String t;
  final int i;

  const Test(this.pressMe, this.t, this.i);
}

```

**Comment by fabianbrandscheid** [comment]
Accidentally closed

**Comment by fabianbrandscheid** [comment]
ohh yeah that was a mistake in the example. In my original code all passed functions are top level.

But it turns out my problem was elsewhere. I wrapped the worker_manager in a separate class and passed only the function containing the arguments. This did not work for some reasons. When I pass the function and the arguments separately and then call the worker_manager it works fine. 
```

// Did NOT work

await this.executorManager.execute<ResultModel>(
                function: ()  =>
                    getJson(myModel),
              )
...

@override
  Future<R> execute<R>({
    required R Function() function,
  }) async {
    try {
      return await workerManager.execute<R>(function);;
    } catch (ex) {
      this._logger.error("error during execution $ex");
      rethrow;
    }
  }

------------------------------

//Works

await this
              .executorManager
              .execute<ArgsType, ResultModel >(
                argument: args,
                function: getJson,
              )


  @override
  Future<R> execute<T, R>({
    required T argument,
    required R Function(T) function,
  }) async {
    try {
      return await  workerManager.execute<R>(() => function(argument));
    }
    } catch (ex) {
      this._logger.error("error during execution $ex");
      rethrow;
    }
  }
```

Thank you very much!

**Comment by milesegan** [comment]
For future reference this seems possibly related to: https://github.com/dart-lang/sdk/issues/36983

I had a similar issue with this and worker_manager and was able to work around it by moving the argument that gets passed to `workerManager.execute` to a top-level function that creates a function instead of an inline closure.

**Comment by machinescream** [comment]
Well, as far as i understand it seems like the old api with top level function could extend some functionality. I will try to support both ways, but to be honest, it should dart related issue

**Comment by milesegan** [comment]
@machinescream I think it's ok to leave this closed. I agree it's an issue that needs to be addressed in dart itself.

The only thing you could maybe do here is have an alternate `execute` that makes it a bit easier to avoid a closure.

**Comment by machinescream** [comment]
> @machinescream I think it's ok to leave this closed. I agree it's an issue that needs to be addressed in dart itself.
> 
> The only thing you could maybe do here is have an alternate `execute` that makes it a bit easier to avoid a closure.

i think you can solve your problem by getting data structure from std lib if you are parsing json it could be Map<String,dynamic> and then you have a result, you can construct your instance of class in main isolate. Is it good compromise for you, what do you think? I have decided to use lambdas other function + argument api because it is much more easier and natively way of use isolates. Anyway, if you dont need new features from worker_manager - you can use old worker_manager with old api. If it is incompatible with some new libraries, pls, let me know. Closing issue for now.

**Comment by nomiuo** [comment]
Hi, I met the same problem agagin.

The flutter version: Channel stable, 3.16.4;
Dart version: 3.2.3 (stable);
worker_manager version: ^6.3.1

Here is the error code, you can run it after installing hive and hive_flutter by `flutter pub add hive hive_flutter`. PS: I await the workManager just to debug. In the real case, I use the unawait.:
```dart
import 'package:flutter/services.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:worker_manager/worker_manager.dart';

void main() async {
  // Init the component.
  await workerManager.init();
  await Hive.initFlutter();

  final Box<dynamic> cache = await Hive.openBox('test');

  final RootIsolateToken rootIsolateToken = RootIsolateToken.instance!;
  await workerManager
      .execute(() => lowerCaseStringInMockChannel('ABC', rootIsolateToken))
      .then((String value) {
    cache.put(value, value);
    print(value);
  });
}

Future<String> lowerCaseStringInMockChannel(
    String string, RootIsolateToken rootIsolateToken) async {
  BackgroundIsolateBinaryMessenger.ensureInitialized(rootIsolateToken);
  return string.toLowerCase();
}
```
Here is the error:
```
E/flutter (23245): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _Future@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)
E/flutter (23245):  <- _writeTask in Instance of 'ReadWriteSync' (from package:hive/src/backend/vm/read_write_sync.dart)
E/flutter (23245):  <- _sync in Instance of 'StorageBackendVm' (from package:hive/src/backend/vm/storage_backend_vm.dart)
E/flutter (23245):  <- Instance of 'BoxImpl<dynamic>' (from package:hive/src/box/box_impl.dart)
E/flutter (23245):  <- Context num_variables: 2 <- Closure: () => Future<String> (from package:orange_photo_album/src/test.dart)
E/flutter (23245): 
E/flutter (23245): #0      _SendPort._sendInternal (dart:isolate-patch/isolate_patch.dart:250:43)
E/flutter (23245): #1      _SendPort.send (dart:isolate-patch/isolate_patch.dart:231:5)
E/flutter (23245): #2      WorkerImpl.work (package:worker_manager/src/worker/worker_io.dart:68:15)
E/flutter (23245): <asynchronous suspension>
E/flutter (23245): #3      _Executor._schedule.<anonymous closure> (package:worker_manager/src/scheduling/executor.dart:141:37)
E/flutter (23245): <asynchronous suspension>
E/flutter (23245): #4      _Executor._schedule.<anonymous closure> (package:worker_manager/src/scheduling/executor.dart:145:21)
E/flutter (23245): <asynchronous suspension>
```

What I am trying to do is calling the method in android, and before that, I must use RootIsolateToken to initialize the isolate, otherwise it will throw an exception. Then put the result into the database which is hive here.

We can fix it if we do not pass in the RootIsolateToken argument like this:
```dart
import 'package:hive_flutter/hive_flutter.dart';
import 'package:worker_manager/worker_manager.dart';

void main() async {
  // Init the component.
  await workerManager.init();
  await Hive.initFlutter();

  final Box<dynamic> cache = await Hive.openBox('test');

  await workerManager
      .execute(() => lowerCaseStringInMockChannel('ABC'))
      .then((String value) {
    cache.put(value, value);
    print(value);
  });
}

Future<String> lowerCaseStringInMockChannel(String string) async {
  return string.toLowerCase();
}
```
It works without initialize channel, but I really need this...

The second solution is that not use Hive in the callback function.
```dart
import 'package:flutter/services.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:worker_manager/worker_manager.dart';

void main() async {
  // Init the component.
  await workerManager.init();
  await Hive.initFlutter();

  final Box<dynamic> cache = await Hive.openBox('test');

  final RootIsolateToken rootIsolateToken = RootIsolateToken.instance!;
  await workerManager
      .execute(() => lowerCaseStringInMockChannel('ABC', rootIsolateToken))
      .then((String value) {
    // cache.put(value, value); It works without hive box.
    print(value);
  });
}

Future<String> lowerCaseStringInMockChannel(
    String string, RootIsolateToken rootIsolateToken) async {
  BackgroundIsolateBinaryMessenger.ensureInitialized(rootIsolateToken);
  return string.toLowerCase();
}
```

It is easy to use a local variable to store the value returned by isolate instead of using it in callback. But In this way, the function will be sync instead of async. We have to wait the result...
```dart
import 'package:flutter/services.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:worker_manager/worker_manager.dart';

void main() async {
  // Init the component.
  await workerManager.init();
  await Hive.initFlutter();

  final Box<dynamic> cache = await Hive.openBox('test');

  String value = "";
  final RootIsolateToken rootIsolateToken = RootIsolateToken.instance!;
  await workerManager
      .execute(() => lowerCaseStringInMockChannel('ABC', rootIsolateToken))
      .then((String value) {
    value = value;
    print(value);
  });

  cache.put(value, value);
}

Future<String> lowerCaseStringInMockChannel(
    String string, RootIsolateToken rootIsolateToken) async {
  BackgroundIsolateBinaryMessenger.ensureInitialized(rootIsolateToken);
  return string.toLowerCase();
}
```

May I ask why it will throw an exception?
